name: PlatformIO Build Check

on:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.13.2' 

      - name: Install PlatformIO Core
        run: pip install -U platformio

      - name: Build Project
        run: pio run -e freenove_esp32_s3_wroom 